services:
  - type: web
    name: comunidade-sinfonica
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
